### ISSUE TITLE
Can we add a standard license to this?

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/ontotools-docker#3]

**Comment by matentzn** [comment]
I am not really good with licenses - what license should we use? Do you have recommendations?

**Comment by udp** [comment]
We could add the Apache 2 license that OLS uses: 

https://github.com/EBISPOT/OLS/blob/main/LICENSE

**Comment by udp** [comment]
@matentzn  is that ok with you?

**Comment by matentzn** [comment]
I dont mind, whatever works!
