### ISSUE TITLE
List of custom OntoTools installations - SemLookP

### ISSUE THREAD

**Issue by rombaum** [EBISPOT/ontotools-docker#4]
Hi @matentzn ,

sadly I'm a little bit late with my response, but I would love to contribute how we would like to use OLS and OxO for our research for your [overview](https://github.com/EBISPOT/ontotools-docker-config/blob/master/docs/custom_ontotools_users.md). 

---

### SemLookP

The Semantic Lookup Platform **SemLookP** hosted by the [ZB MED - Information Centre for Life Sciences](https://www.zbmed.de/en/) should be used in the biomedical domain. We want to use the system as a backbone service for different other services. SemLookP should help us in the following task:

- Create (semi-)automatic annotations for research data
- Set up an enriched semantic search service
- Give additional information about a specific terminology resource

Our SemLookP services are accessible under:
- terminology service: https://semanticlookup.zbmed.de/ols/index
- mapping service: https://semanticlookup.zbmed.de/mappings/

One of our first use cases where we use SemLookP to show additional information for a concept is our COVID-19 preprint viewer [preVIEW](https://preview.zbmed.de/).

---

I hope the content fits the page. If you need anything else just contact me.

Best,

Roman

**Comment by matentzn** [comment]
@rombaum Roman, this is great! Thanks for sharing. I assume you are not using docker, but a completely customised fork of OLS/OxO right? Would you be able to describe a bit the kind of changes you did in the source code to enable your customised version?

**Comment by rombaum** [comment]
Hi @matentzn Nico,

we created a fork in December 2019 and created an own docker. But I also tested it last week with the docker of OLS on my local machine. To run OLS just with an individual frontend you just have to change the following two files:

- The value of line 24 in the [docker-compose file](https://github.com/EBISPOT/OLS/blob/57bd029a1560ccff15586c20e2490f0761029296/docker-compose.yml#L24)
- Add a new module for the customized frontend in the [pom.xml](https://github.com/EBISPOT/OLS/blob/57bd029a1560ccff15586c20e2490f0761029296/pom.xml#L59)

Next to this to small changes you could start to create your own frontend by duplicating the module 'ols-web'. So if there are any changed in the original code we only have to adapt the changed of our customized frontend module 'ols-web'.

Some highlights we did:

- [ordered the database cross references in alphanumerical order](https://semanticlookup.zbmed.de/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000400)
  -  Also hyperlinks will appear at the beginning of the list
- [added a hyperlink functionality when the creators of an ontology are hyperlinks ](https://semanticlookup.zbmed.de/ols/ontologies/mesh)
  - possible to use FAIR identifiers
  - it is also more interactive
- made the frontend also a little bit more responsive

Independently from these frontend changes we also played a little bit around and updated some technologies inside of our OLS version:
- [upgraded MongoDB Java Driver from 2.14.3 to the newest version 3.12.3](https://github.com/EBISPOT/OLS/pull/353) 
  - sadly it was never merged into your code
- we also updated the embedded Neo4j version from 2.2.2 to 2.3.12
  - but was I already spotted that you want to update this old version to a [much newer version of Neo4j](https://github.com/EBISPOT/OLS/issues/426). That would be awesome.

**Comment by matentzn** [comment]
Thank you so much for the detailed response! Very nice work!

**Comment by matentzn** [comment]
Check https://github.com/EBISPOT/OLS/pull/482

**Comment by matentzn** [comment]
https://ols.ccdh.io/ontologies/ncit_plus

**Comment by matentzn** [comment]
https://terminology.nfdi4chem.de/ts

**Comment by matentzn** [comment]
https://ols.monarchinitiative.org/

**Comment by matentzn** [comment]
https://terminology.tib.eu/ts/index

**Comment by rombaum** [comment]
> https://terminology.tib.eu/ts/index

This is the main instance from the TIB services. Next to the one from [NFDI4Chem](https://github.com/EBISPOT/ontotools-docker/issues/4#issuecomment-871995885) you could also found one for NFDI4ING

https://terminology.nfdi4ing.de/ts/

These three are using the same backend and using the parameter _**collection**_ to identify the wished subset of ontologies in the TIB General.

**Comment by rombaum** [comment]
https://ols.imise.uni-leipzig.de/ontologies/anno

**Comment by rombaum** [comment]
@jonquet in this issue branch is an overview of OLS instances. Also there is an [overview](https://github.com/EBISPOT/ontotools-docker-config/blob/master/docs/custom_ontotools_users.md) created by @matentzn

**Comment by jonquet** [comment]
> @jonquet in this issue branch is an overview of OLS instances. Also there is an [overview](https://github.com/EBISPOT/ontotools-docker-config/blob/master/docs/custom_ontotools_users.md) created by @matentzn

Ok. Those instances of OLS are all reported in FAIR-IMPACT's study.
